const express = require('express');
const router = express.Router();

const authRoutes = require('./user/authRoutes');
const productRoutes = require('./product/productRoutes');
const categoryRoutes = require('./category/categoryRoutes');
const cartRoutes = require('./cart/cartRoutes');
const contactRoutes = require('./contact/contact');
const chatbotRoutes = require('./chatbot/chatbotRoutes');
const userProfileRoutes = require('./user/profileRoutes');
const orderRoutes = require('./order/orderRoutes');
const payoutRoutes = require('./payout/payoutRoutes');
const addressesRoutes = require('./addresses/addressesRoutes');
const sellerRoutes = require('./seller/seller');
const referralRoutes = require('./referral/referralRoutes');
const policyRoutes = require('./policy/policyRoutes');
const driverRoutes = require('./driver/driverAuth');
const driverEarningRoutes = require('./driverEarnings/driverEarnings');
const driverOrderRoutes = require('./driver/driverRoutes');
const driverWithdrawRoutes = require('./withdraw/withdraw');
const driverPayoutRoutes = require('./driverPayout/driverPayoutRoutes');
const adminRoutes = require('./admin/adminRoutes');
const adminDashboardRoutes = require('./dashboard/dashboardRoutes');
const adminUserRoutes = require('./admin/user/adminUserRoutes');
const adminRoleRoutes = require('./admin/role/roleRoutes');
const adminPromotorRoutes = require('./admin/promotor/promotor');
const adminWarehouseRoutes = require('./admin/warehouse/warehouseRoutes');
const adminDriverRoutes = require('./admin/driver/driver');
const adminOrderRoutes = require('./admin/order/order');
const adminBannerRoutes = require('./admin/banner/banner');
const adminCouponRoutes = require('./admin/coupon/coupon');
const adminDiscountRoutes = require('./admin/discount/discount');
const adminSellerRoutes = require('./admin/seller/seller');
const adminTermsRoutes = require('./admin/termsAndConditions/terms');
const adminProductRoutes = require('./admin/product/product');
const notificationRoutes = require('./notificationRoutes');
const sellerShopRoutes = require('./seller/shopRoutes');
const publicShopRoutes = require('./public/shopRoutes');
const adminShopRoutes = require('./admin/shopRoutes');
const adminPopupRoutes = require('./admin/popupRoutes');
const promotorRoutes = require('./promotor/promotorRoutes');
const adminReportRoutes = require('./admin/report/report');
const warehouseRoutes = require('./warehouse/warehouseRoutes');
const adminPaymentSettingsRoutes = require('./admin/paymentSettingsRoutes');

const publicPopupRouter = express.Router();
publicPopupRouter.get('/active', require('../controllers/admin/popupController').getActivePopup);

router.use('/api/user', authRoutes);
router.use('/api/user/profile', userProfileRoutes);
router.use('/api/user/addresses', addressesRoutes);
router.use('/api/product', productRoutes);
router.use('/api/category', categoryRoutes);
router.use('/api/cart', cartRoutes);
router.use('/api/contact', contactRoutes);
router.use('/api/chatbot', chatbotRoutes);
router.use('/api/order', orderRoutes);
router.use('/api/payout', payoutRoutes);
router.use('/api/seller', sellerRoutes);
router.use('/api/promotor', promotorRoutes);
router.use('/api/seller/shop', sellerShopRoutes);
router.use('/api/shops', publicShopRoutes);
router.use('/api/referral', referralRoutes);
router.use('/api/driver', driverRoutes);
router.use('/api/driver', driverOrderRoutes);
router.use('/api/driver-earnings', driverEarningRoutes);
router.use('/api/driver/withdraw', driverWithdrawRoutes);
router.use('/api/driver/payout', driverPayoutRoutes);
router.use('/api/policy', policyRoutes);
router.use('/api/notifications', notificationRoutes);
router.use('/api/admin/roles', adminRoleRoutes);
router.use('/api/admin/dashboard', adminDashboardRoutes);
router.use('/api/admin/promotor', adminPromotorRoutes);
router.use('/api/admin/warehouse', adminWarehouseRoutes);
router.use('/api/admin/drivers', adminDriverRoutes);
router.use('/api/admin/orders', adminOrderRoutes);
router.use('/api/admin/banners', adminBannerRoutes);
router.use('/api/admin/coupon', adminCouponRoutes);
router.use('/api/admin/discount', adminDiscountRoutes);
router.use('/api/admin/seller', adminSellerRoutes);
router.use('/api/admin/terms', adminTermsRoutes);
router.use('/api/admin/products', adminProductRoutes);
router.use('/api/admin/shops', adminShopRoutes);
router.use('/api/admin/popups', adminPopupRoutes);
router.use('/api/popups', publicPopupRouter);
router.use('/api/admin/payment-settings', adminPaymentSettingsRoutes);
router.use('/api/admin', adminUserRoutes);
router.use('/api/admin', adminRoutes);
router.use('/api/admin/reports', adminReportRoutes);
router.use('/api/warehouse', warehouseRoutes);

module.exports = router;
